#!/bin/bash

# Aaron Stump, Tjark Weber
# A simple post-processor for SMT.

set -e
set -u

# if the output file ($1) does not contain the word "sat", set SAT to 0
SAT=1
grep -qsw sat "$1" || SAT=0

UNSAT=1
grep -qsw unsat "$1" || UNSAT=0

UNKNOWN=1
grep -qsw unknown "$1" || UNKNOWN=0

if [[ "$SAT" -eq 1 && "$UNSAT" -eq 0 && "$UNKNOWN" -eq 0 ]]; then
    # the output contains only the word "sat"
    echo "starexec-result=sat"
elif [[ "$SAT" -eq 0 && "$UNSAT" -eq 1 && "$UNKNOWN" -eq 0 ]]; then
    # the output contains only the word "unsat"
    echo "starexec-result=unsat"
else
    echo "starexec-result=starexec-unknown"
fi
