#!/bin/bash
# Included in bin

SOLVER=cyclist
EXT=defs

FILE=`basename $1`
SL2SL=./bin/slcomp-parser
SL2SOLVER=./bin/compile

cp $1 $FILE
rm -f $FILE.sl14* file_*
./bin/slcomp-parser --config ./input/input.prop --output SL_COMP14 $FILE 1> $FILE.sl14 2>err1.log
./bin/compile -cyclist $FILE.sl14 &>err2.log
rm -f $FILE $FILE.sl14 
cat $FILE.sl14.$EXT

