#!/bin/sh
# Included in bin

#SOLVER
EXT=smt

FILE=`basename $1`
SL2SL=./bin/slcomp-parser
SL2SOLVER=./bin/compile

cp $1 ${FILE}
$SL2SL --config ./input/input.prop --output SL_COMP14 $FILE 1> $FILE.$EXT 2>/dev/null
rm ${FILE} 
cat ${FILE}.$EXT

