
#line 3 "lex.smt_yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer smt_yy_create_buffer
#define yy_delete_buffer smt_yy_delete_buffer
#define yy_flex_debug smt_yy_flex_debug
#define yy_init_buffer smt_yy_init_buffer
#define yy_flush_buffer smt_yy_flush_buffer
#define yy_load_buffer_state smt_yy_load_buffer_state
#define yy_switch_to_buffer smt_yy_switch_to_buffer
#define yyin smt_yyin
#define yyleng smt_yyleng
#define yylex smt_yylex
#define yylineno smt_yylineno
#define yyout smt_yyout
#define yyrestart smt_yyrestart
#define yytext smt_yytext
#define yywrap smt_yywrap
#define yyalloc smt_yyalloc
#define yyrealloc smt_yyrealloc
#define yyfree smt_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE smt_yyrestart(smt_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t smt_yyleng;

extern FILE *smt_yyin, *smt_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE smt_yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-smt_yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < smt_yyleng; ++yyl )\
                    if ( smt_yytext[yyl] == '\n' )\
                        --smt_yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up smt_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up smt_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via smt_yyrestart()), so that the user can continue scanning by
	 * just pointing smt_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when smt_yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t smt_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow smt_yywrap()'s to do buffer switches
 * instead of setting up a fresh smt_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void smt_yyrestart (FILE *input_file  );
void smt_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE smt_yy_create_buffer (FILE *file,int size  );
void smt_yy_delete_buffer (YY_BUFFER_STATE b  );
void smt_yy_flush_buffer (YY_BUFFER_STATE b  );
void smt_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void smt_yypop_buffer_state (void );

static void smt_yyensure_buffer_stack (void );
static void smt_yy_load_buffer_state (void );
static void smt_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER smt_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE smt_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE smt_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE smt_yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *smt_yyalloc (yy_size_t  );
void *smt_yyrealloc (void *,yy_size_t  );
void smt_yyfree (void *  );

#define yy_new_buffer smt_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        smt_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            smt_yy_create_buffer(smt_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        smt_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            smt_yy_create_buffer(smt_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define smt_yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *smt_yyin = (FILE *) 0, *smt_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int smt_yylineno;

int smt_yylineno = 1;

extern char *smt_yytext;
#define yytext_ptr smt_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up smt_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	smt_yyleng = (yy_size_t) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[314] =
    {   0,
        0,    0,    0,    0,    0,    0,   71,   70,   68,   67,
        2,   57,   70,   55,    9,   10,   11,   11,   70,   70,
       55,   55,   55,    1,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   62,   61,   59,
       59,   60,   66,   63,   63,   65,   64,   67,   55,    0,
        0,    0,   11,   56,   56,   56,   56,    0,   69,   69,
       55,   55,   55,    3,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       59,   58,   63,   14,   13,   12,   12,   56,   56,   56,
       56,   55,   55,   55,   55,   55,   55,   55,   55,   55,

       55,   55,    4,   55,   55,   15,    8,   40,   55,   55,
       55,   55,   12,   56,   56,   56,   55,   55,   55,   55,
       55,   55,   55,   29,   55,   30,   55,   55,   55,   55,
       41,   55,   55,   55,   53,   56,   56,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   51,    7,   43,   55,   55,   55,   55,
       52,   56,   55,   55,   49,   16,   55,   55,   55,    5,
        6,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   50,   56,   47,   48,   55,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,

       56,   55,   55,   55,   55,   55,   55,   33,   55,   55,
       55,   55,   55,   55,   44,   55,   55,   54,   18,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   34,   55,
       36,   55,   39,   55,   45,   55,   55,   55,   55,   55,
       55,   55,   27,   55,   55,   55,   35,   55,   55,   46,
       55,   55,   55,   22,   55,   55,   55,   55,   28,   55,
       55,   55,   55,   55,   55,   55,   55,   24,   23,   55,
       55,   55,   55,   55,   55,   55,   55,   19,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   26,   55,
       31,   32,   55,   38,   55,   55,   55,   25,   55,   55,

       55,   20,   55,   42,   55,   21,   55,   17,   55,   55,
       55,   37,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    8,    8,    8,    1,    9,
       10,    8,    8,    1,   11,   12,    8,   13,   14,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,    8,
        8,    8,    8,    8,   18,   19,   20,   21,   22,   19,
       23,   24,   25,   24,   24,   26,   27,   28,   24,   24,
       24,   29,   30,   31,   32,   24,   24,   24,   24,   24,
        1,   33,    1,    8,   34,    1,   35,   36,   37,   38,

       39,   40,   41,   42,   43,   24,   44,   45,   46,   47,
       48,   49,   24,   50,   51,   52,   53,   54,   24,   55,
       56,   24,    1,   57,    1,    8,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[58] =
    {   0,
        1,    1,    1,    1,    2,    1,    1,    2,    1,    1,
        2,    2,    3,    3,    3,    1,    1,    4,    4,    4,
        4,    4,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    1,    2,    4,    4,    4,    4,    4,    4,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    1
    } ;

static yyconst flex_int16_t yy_base[321] =
    {   0,
        0,    0,   55,   59,   63,   65,  392,  393,  393,   67,
        0,  393,   24,    0,  393,  393,  379,   60,   36,   74,
      368,  357,  357,    0,  336,  344,  346,   27,  336,  344,
       41,  347,  333,   46,  341,  340,  336,  393,  393,   80,
       82,  371,  393,   87,   89,  393,  393,   97,    0,   89,
        0,   91,   95,    0,  323,  327,  332,  108,  110,  112,
      353,  345,  342,  319,  330,   81,  326,  324,  316,  313,
      312,  322,  310,  309,  310,  310,  307,  306,  304,  316,
      120,  393,  122,  114,    0,  116,  119,    0,  307,  303,
      313,  326,  328,  324,  309,  310,  301,  302,  296,   84,

      308,  331,    0,  298,  303,    0,    0,    0,  297,  299,
      326,  288,  124,  284,  282,  285,  305,  302,  302,  279,
      284,  292,  279,    0,  273,    0,  279,  105,  286,  280,
        0,  269,   98,  270,    0,  268,  268,  299,  298,  292,
      262,  302,  262,  272,  259,  264,  257,  260,  258,  256,
      254,  256,  267,    0,    0,  290,  253,  251,  249,  241,
        0,  253,  269,  268,    0,    0,  242,  253,  280,    0,
        0,  239,  249,  250,  235,  238,  234,  239,  248,  242,
      240,  228,    0,  240,    0,    0,  243,  266,  104,  106,
      228,  236,  231,  225,  237,  218,  219,  221,  225,  224,

      215,  213,  123,  211,  215,  212,  220,    0,  215,  211,
      218,  205,  217,  204,    0,  217,  205,    0,  241,  203,
      215,  196,  209,  199,  199,  195,  192,  196,    0,  195,
        0,  230,    0,  201,    0,  192,  203,  190,  184,  188,
      199,  183,  106,  180,  188,  184,    0,   60,  179,    0,
      177,  176,  191,    0,  176,  172,  173,  211,    0,  173,
      181,  168,  170,  165,  165,  163,  162,    0,    0,  174,
      162,  164,  163,  158,  158,  164,  153,    0,  149,  167,
      164,  151,  149,  147,  160,  150,  141,  124,    0,  135,
        0,    0,  125,    0,  123,  126,  129,    0,  118,  115,

      117,  111,  104,    0,  111,    0,  107,    0,   99,   95,
       68,    0,  393,  174,  178,  181,  184,  188,  190,  193
    } ;

static yyconst flex_int16_t yy_def[321] =
    {   0,
      313,    1,  314,  314,  315,  315,  313,  313,  313,  313,
      316,  313,  313,  316,  313,  313,  313,  313,  317,  318,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  316,  313,
      319,  313,  313,  320,  320,  320,  320,  318,  313,  318,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      313,  313,  313,  313,  319,  313,  313,  320,  320,  320,
      320,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  313,  320,  320,  320,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  320,  320,  320,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      320,  320,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  320,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      320,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  320,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,

      316,  316,  316,  316,  316,  316,  316,  316,  316,  316,
      316,  316,    0,  313,  313,  313,  313,  313,  313,  313
    } ;

static yyconst flex_int16_t yy_nxt[451] =
    {   0,
        8,    9,   10,   10,   11,   12,   13,   14,   15,   16,
       14,   14,   17,   18,   18,   19,   20,   14,   14,   14,
       21,   14,   14,   14,   14,   14,   14,   22,   14,   23,
       14,   14,    8,   24,   25,   14,   26,   27,   28,   29,
       30,   14,   14,   14,   31,   32,   33,   14,   34,   35,
       36,   37,   14,   14,   14,   14,   38,   40,   41,   50,
       42,   40,   41,   67,   42,   44,   45,   44,   45,   48,
       48,   52,   53,   53,   53,   55,   59,   60,   51,   71,
       75,   68,   81,   81,   81,   81,   56,   57,   72,   83,
       83,   83,   83,   76,  262,   46,  263,   46,   77,   48,

       48,   84,   84,   86,   87,   87,   52,   53,   53,   53,
       59,   60,   59,   59,   59,   60,  257,   97,  312,   47,
       98,   47,   81,   81,   83,   83,   84,   84,   86,   87,
       87,  113,  113,  113,  125,  126,  113,  113,  113,  147,
      157,  311,  158,  204,  206,  159,  310,  148,  207,  309,
      149,  308,  150,  151,  205,  307,  258,  152,  153,  220,
      221,  306,  222,  305,  223,  304,  303,  302,  301,  300,
      299,  298,  297,  224,   39,   39,   39,   39,   43,   43,
       43,   43,   49,   49,   49,   54,  296,   54,   58,   58,
       58,   58,   85,   85,   88,   88,   88,  295,  294,  293,

      292,  291,  290,  289,  288,  287,  286,  285,  284,  283,
      282,  281,  280,  279,  278,  277,  276,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  261,
      260,  259,  256,  255,  254,  253,  252,  251,  250,  249,
      248,  247,  246,  245,  244,  243,  242,  241,  240,  239,
      238,  237,  236,  235,  234,  233,  232,  231,  230,  229,
      228,  227,  226,  225,  219,  218,  217,  216,  215,  214,
      213,  212,  211,  210,  209,  208,  203,  202,  201,  200,
      199,  198,  197,  196,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  182,  181,  180,

      179,  178,  177,  176,  175,  174,  173,  172,  171,  170,
      169,  168,  167,  166,  165,  164,  163,  162,  161,  160,
      156,  155,  154,  146,  145,  144,  143,  142,  141,  140,
      139,  138,  137,  136,  135,  134,  133,  132,  131,  130,
      129,  128,  127,  124,  123,  122,  121,  120,  119,  118,
      117,  116,  115,  114,  112,  111,  110,  109,  108,  107,
      106,  105,  104,  103,  102,  101,  100,   99,   96,   95,
       94,   93,   92,   91,   90,   89,   82,   80,   79,   78,
       74,   73,   70,   69,   66,   65,   64,   63,   62,   61,
       52,  313,    7,  313,  313,  313,  313,  313,  313,  313,

      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313
    } ;

static yyconst flex_int16_t yy_chk[451] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,   13,
        3,    4,    4,   28,    4,    5,    5,    6,    6,   10,
       10,   18,   18,   18,   18,   19,   20,   20,   13,   31,
       34,   28,   40,   40,   41,   41,   19,   19,   31,   44,
       44,   45,   45,   34,  248,    5,  248,    6,   34,   48,

       48,   50,   50,   52,   52,   52,   53,   53,   53,   53,
       58,   58,   59,   59,   60,   60,  243,   66,  311,    5,
       66,    6,   81,   81,   83,   83,   84,   84,   86,   86,
       86,   87,   87,   87,  100,  100,  113,  113,  113,  128,
      133,  310,  133,  189,  190,  133,  309,  128,  190,  307,
      128,  305,  128,  128,  189,  303,  243,  128,  128,  203,
      203,  302,  203,  301,  203,  300,  299,  297,  296,  295,
      293,  290,  288,  203,  314,  314,  314,  314,  315,  315,
      315,  315,  316,  316,  316,  317,  287,  317,  318,  318,
      318,  318,  319,  319,  320,  320,  320,  286,  285,  284,

      283,  282,  281,  280,  279,  277,  276,  275,  274,  273,
      272,  271,  270,  267,  266,  265,  264,  263,  262,  261,
      260,  258,  257,  256,  255,  253,  252,  251,  249,  246,
      245,  244,  242,  241,  240,  239,  238,  237,  236,  234,
      232,  230,  228,  227,  226,  225,  224,  223,  222,  221,
      220,  219,  217,  216,  214,  213,  212,  211,  210,  209,
      207,  206,  205,  204,  202,  201,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  188,  187,  184,  182,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      169,  168,  167,  164,  163,  162,  160,  159,  158,  157,

      156,  153,  152,  151,  150,  149,  148,  147,  146,  145,
      144,  143,  142,  141,  140,  139,  138,  137,  136,  134,
      132,  130,  129,  127,  125,  123,  122,  121,  120,  119,
      118,  117,  116,  115,  114,  112,  111,  110,  109,  105,
      104,  102,  101,   99,   98,   97,   96,   95,   94,   93,
       92,   91,   90,   89,   80,   79,   78,   77,   76,   75,
       74,   73,   72,   71,   70,   69,   68,   67,   65,   64,
       63,   62,   61,   57,   56,   55,   42,   37,   36,   35,
       33,   32,   30,   29,   27,   26,   25,   23,   22,   21,
       17,    7,  313,  313,  313,  313,  313,  313,  313,  313,

      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  313,  313,  313,  313,  313,  313,  313
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[71] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int smt_yy_flex_debug;
int smt_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *smt_yytext;
#line 1 "smtlib-flex-lexer.l"
#line 2 "smtlib-flex-lexer.l"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "smtlib-glue.h" 
#include "smtlib-bison-parser.y.h"

int smt_yycolumn = 1;
#define UPDATE_COLUMN(n) smt_yycolumn += n;

#define RESET_COLUMN smt_yycolumn = 1;

#define SET_LOCATION smt_yylloc.first_line = smt_yylloc.last_line = smt_yylineno; \
smt_yylloc.first_column = smt_yycolumn; smt_yylloc.last_column = smt_yycolumn + smt_yyleng - 1; \
UPDATE_COLUMN(smt_yyleng);

#define SET_LEFT smt_yylloc.first_line = smt_yylineno; \
smt_yylloc.first_column = smt_yycolumn; \
UPDATE_COLUMN(smt_yyleng);

#define SET_RIGHT smt_yylloc.last_line = smt_yylineno; \
smt_yylloc.last_column = smt_yycolumn + smt_yyleng - 1; \
UPDATE_COLUMN(smt_yyleng);


#line 722 "lex.smt_yy.c"

#define INITIAL 0
#define string 1
#define quoted 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int smt_yylex_destroy (void );

int smt_yyget_debug (void );

void smt_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE smt_yyget_extra (void );

void smt_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *smt_yyget_in (void );

void smt_yyset_in  (FILE * in_str  );

FILE *smt_yyget_out (void );

void smt_yyset_out  (FILE * out_str  );

yy_size_t smt_yyget_leng (void );

char *smt_yyget_text (void );

int smt_yyget_lineno (void );

void smt_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int smt_yywrap (void );
#else
extern int smt_yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( smt_yytext, smt_yyleng, 1, smt_yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( smt_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( smt_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, smt_yyin))==0 && ferror(smt_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(smt_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int smt_yylex (void);

#define YY_DECL int smt_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after smt_yytext and smt_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 49 "smtlib-flex-lexer.l"


#line 909 "lex.smt_yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! smt_yyin )
			smt_yyin = stdin;

		if ( ! smt_yyout )
			smt_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			smt_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				smt_yy_create_buffer(smt_yyin,YY_BUF_SIZE );
		}

		smt_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (yy_c_buf_p) - (yytext_ptr);
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of smt_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 314 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 393 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = (yy_more_len); yyl < smt_yyleng; ++yyl )
				if ( smt_yytext[yyl] == '\n' )
					   
    smt_yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 51 "smtlib-flex-lexer.l"
{ SET_LOCATION; return '_'; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 52 "smtlib-flex-lexer.l"
{ SET_LOCATION; return '!'; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_AS; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 54 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_LET; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 55 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_EXISTS; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 56 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_FORALL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 57 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_MATCH; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 58 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_PAR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 60 "smtlib-flex-lexer.l"
{ SET_LOCATION; return '('; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "smtlib-flex-lexer.l"
{ SET_LOCATION; return ')'; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 63 "smtlib-flex-lexer.l"
{ 
						SET_LOCATION;
						smt_yylval.ptr = ast_newNumeralLiteral(
							strtol(smt_yytext, NULL, 10), 10); 
						return NUMERAL; 
					}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 70 "smtlib-flex-lexer.l"
{
						SET_LOCATION;
						smt_yylval.ptr = ast_newDecimalLiteral(
							strtod(smt_yytext, NULL));  
						return DECIMAL; 
					}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 76 "smtlib-flex-lexer.l"
{ 
						SET_LOCATION;
						smt_yylval.ptr = ast_newNumeralLiteral(
							strtol(smt_yytext+2, NULL, 16), 16); 
						return HEXADECIMAL; 
					}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 82 "smtlib-flex-lexer.l"
{
						SET_LOCATION;
						smt_yylval.ptr = ast_newNumeralLiteral(
							strtol(smt_yytext+2, NULL, 2), 2); 
						return BINARY; 
					}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 88 "smtlib-flex-lexer.l"
{ SET_LOCATION; return NOT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 90 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_ASSERT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 91 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_CHK_SAT_ASSUM; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 92 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_CHK_SAT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 93 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_DECL_CONST; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 94 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_DECL_DATATYPE; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 95 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_DECL_DATATYPES; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 96 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_DECL_FUN; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 97 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_DECL_SORT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 98 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_DECL_HEAP; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 99 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_DEF_FUNS_REC; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 100 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_DEF_FUN_REC; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 101 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_DEF_FUN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 102 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_DEF_SORT; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 103 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_ECHO; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 104 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_EXIT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 105 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_GET_ASSERTS; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 106 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_GET_ASSIGNS; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 107 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_GET_INFO; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 108 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_GET_MODEL; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 109 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_GET_OPT; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 110 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_GET_PROOF; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 111 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_GET_UNSAT_ASSUMS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 112 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_GET_UNSAT_CORE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 113 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_GET_VALUE; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 114 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_POP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 115 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_PUSH; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 116 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_RESET_ASSERTS; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 117 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_RESET; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 118 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_SET_INFO; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 119 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_SET_LOGIC; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 120 "smtlib-flex-lexer.l"
{ SET_LOCATION; return KW_SET_OPT; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 122 "smtlib-flex-lexer.l"
{ 
				SET_LOCATION;
				smt_yylval.ptr = ast_newMetaSpecConstant(1);
				return META_SPEC_DECIMAL; 
			}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 127 "smtlib-flex-lexer.l"
{ 
				SET_LOCATION;
				smt_yylval.ptr = ast_newMetaSpecConstant(0);
				return META_SPEC_NUMERAL; 
			}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 132 "smtlib-flex-lexer.l"
{ 
				SET_LOCATION;
				smt_yylval.ptr = ast_newMetaSpecConstant(2);
				return META_SPEC_STRING; 
			}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 138 "smtlib-flex-lexer.l"
{ 
				SET_LOCATION;
				smt_yylval.ptr = ast_newSymbol(smt_yytext); 
				return THEORY; 
			}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 143 "smtlib-flex-lexer.l"
{ 
				SET_LOCATION;
				smt_yylval.ptr = ast_newSymbol(smt_yytext); 
				return LOGIC; 
			}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 149 "smtlib-flex-lexer.l"
{ 
							SET_LOCATION;
							smt_yylval.ptr = ast_newKeyword(smt_yytext);
							return KW_ATTR_SORTS; 
						}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 154 "smtlib-flex-lexer.l"
{ 
							SET_LOCATION;
							smt_yylval.ptr = ast_newKeyword(smt_yytext);
							return KW_ATTR_FUNS; 
						}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 159 "smtlib-flex-lexer.l"
{
							SET_LOCATION;
							smt_yylval.ptr = ast_newKeyword(smt_yytext); 
							return KW_ATTR_THEORIES; 
						}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 165 "smtlib-flex-lexer.l"
{
						SET_LOCATION;
						smt_yylval.ptr = ast_newSymbol(smt_yytext); 
						return SYMBOL; 
					}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 170 "smtlib-flex-lexer.l"
{ 
						SET_LOCATION;
						smt_yylval.ptr = ast_newKeyword(smt_yytext); 
						return KEYWORD; 
					}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 176 "smtlib-flex-lexer.l"
{ SET_LEFT; BEGIN string; yymore(); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 177 "smtlib-flex-lexer.l"
{ UPDATE_COLUMN(2);; yymore(); }
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 178 "smtlib-flex-lexer.l"
{ RESET_COLUMN; yymore(); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 179 "smtlib-flex-lexer.l"
{ 	
						SET_RIGHT;
						BEGIN 0; 
						smt_yylval.ptr = ast_newStringLiteral(smt_yytext);
						return STRING; 
					}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 185 "smtlib-flex-lexer.l"
{ UPDATE_COLUMN(1); yymore(); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 187 "smtlib-flex-lexer.l"
{ SET_LEFT; BEGIN quoted; yymore(); }
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 188 "smtlib-flex-lexer.l"
{ RESET_COLUMN; yymore(); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 189 "smtlib-flex-lexer.l"
{ 
						SET_RIGHT;
						BEGIN 0; 
						smt_yylval.ptr = ast_newSymbol(smt_yytext);
						return SYMBOL; 
					}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 195 "smtlib-flex-lexer.l"
{ }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 196 "smtlib-flex-lexer.l"
{ UPDATE_COLUMN(1); yymore(); }
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 198 "smtlib-flex-lexer.l"
{ SET_LOCATION; smt_yycolumn = 1; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 199 "smtlib-flex-lexer.l"
{ SET_LOCATION; /*ignore*/ }
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 200 "smtlib-flex-lexer.l"
{ SET_LOCATION; smt_yycolumn = 1; /*ignore*/ }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 201 "smtlib-flex-lexer.l"
ECHO;
	YY_BREAK
#line 1432 "lex.smt_yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(string):
case YY_STATE_EOF(quoted):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed smt_yyin at a new source and called
			 * smt_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = smt_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( smt_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * smt_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of smt_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					smt_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			smt_yyrestart(smt_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) smt_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 314 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 314 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 313);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up smt_yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --smt_yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					smt_yyrestart(smt_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( smt_yywrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve smt_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    smt_yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void smt_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        smt_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            smt_yy_create_buffer(smt_yyin,YY_BUF_SIZE );
	}

	smt_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	smt_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void smt_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		smt_yypop_buffer_state();
	 *		smt_yypush_buffer_state(new_buffer);
     */
	smt_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	smt_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (smt_yywrap()) processing, but the only time this flag
	 * is looked at is after smt_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void smt_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	smt_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE smt_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) smt_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in smt_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) smt_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in smt_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	smt_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with smt_yy_create_buffer()
 * 
 */
    void smt_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		smt_yyfree((void *) b->yy_ch_buf  );

	smt_yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a smt_yyrestart() or at EOF.
 */
    static void smt_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	smt_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then smt_yy_init_buffer was _probably_
     * called from smt_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void smt_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		smt_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void smt_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	smt_yyensure_buffer_stack();

	/* This block is copied from smt_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from smt_yy_switch_to_buffer. */
	smt_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void smt_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	smt_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		smt_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void smt_yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)smt_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in smt_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)smt_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in smt_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE smt_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) smt_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in smt_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	smt_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to smt_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       smt_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE smt_yy_scan_string (yyconst char * yystr )
{
    
	return smt_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to smt_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE smt_yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) smt_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in smt_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = smt_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in smt_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up smt_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		smt_yytext[smt_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = smt_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		smt_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int smt_yyget_lineno  (void)
{
        
    return smt_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *smt_yyget_in  (void)
{
        return smt_yyin;
}

/** Get the output stream.
 * 
 */
FILE *smt_yyget_out  (void)
{
        return smt_yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t smt_yyget_leng  (void)
{
        return smt_yyleng;
}

/** Get the current token.
 * 
 */

char *smt_yyget_text  (void)
{
        return smt_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void smt_yyset_lineno (int  line_number )
{
    
    smt_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see smt_yy_switch_to_buffer
 */
void smt_yyset_in (FILE *  in_str )
{
        smt_yyin = in_str ;
}

void smt_yyset_out (FILE *  out_str )
{
        smt_yyout = out_str ;
}

int smt_yyget_debug  (void)
{
        return smt_yy_flex_debug;
}

void smt_yyset_debug (int  bdebug )
{
        smt_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from smt_yylex_destroy(), so don't allocate here.
     */

    /* We do not touch smt_yylineno unless the option is enabled. */
    smt_yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    smt_yyin = stdin;
    smt_yyout = stdout;
#else
    smt_yyin = (FILE *) 0;
    smt_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * smt_yylex_init()
     */
    return 0;
}

/* smt_yylex_destroy is for both reentrant and non-reentrant scanners. */
int smt_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		smt_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		smt_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	smt_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * smt_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *smt_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *smt_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void smt_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see smt_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 201 "smtlib-flex-lexer.l"
