#!/bin/sh
# Included in bin

SOLVER=slide
EXT=sld

FILE=`basename $1`
SL2SL=./bin/slcomp-parser
SL2SOLVER=./bin/compile

cp $1 ${FILE}
$SL2SL --config ./input/input.prop --output SL_COMP14 $FILE 1> $FILE.sl14 2>/dev/null
$SL2SOLVER -$SOLVER $FILE.sl14 &>/dev/null
rm ${FILE} 
rm $FILE.sl14 
cat ${FILE}.sl14.$EXT

